global:
  image:
    registry:
      createSecret: false
  monitoring:
    enabled: true
  development: true
  configurationSources:
    examplePricing:
      docker:
        image: example-pricing-sideloader:5241-SNAPSHOT
  topology:
    domains:
      - networkEnabler:
          # Single Network Enabler defined for the Domain
          totalPodCount: 1
        pricing:
          configurationSource:
            refName: examplePricing
          filePath: /pricing
          fileName: mtx_pricing_matrixxOne.xml
        subdomains:
          - engines:
              - processing:
                  replicaCount: 1
                  tralb:
                    replicaCount: 1
                publishing:
                  replicaCount: 1
                  tralb:
                    replicaCount: 1
                checkpointing:
                  replicaCount: 1
  features:
    sba5gc: true
    ldapGateway: true
tra:
  replicaCount: 1
activemq:
  replicaCount: 1
gateway-proxy:
  replicaCount: 1
rsgateway:
  replicaCount: 1
  ingress:
    enabled: true
    rules:
      - path: "/"
payment-service:
  replicaCount: 1
event-streamer:
  replicaCount: 1
notifier:
  replicaCount: 1
snmp-exporter:
  replicaCount: 1
matrixxbct:
  replicaCount: 1
mymatrixx:
  enabled: false
